### ISSUE TITLE
Number of parameter does not match expected count.

### ISSUE THREAD

**Issue by kierepka** [nativecode-dev/oss-xamarin#44]
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
... 1 more
Caused by: md52ce486a14f4bcd95899665e9d932190b.JavaProxyThrowable: System.Reflection.TargetParameterCountException: Number of parameter does not match expected count.
at System.Reflection.Binder.ConvertValues (object[],System.Reflection.ParameterInfo[],System.Globalization.CultureInfo,bool) <0x00158>
at System.Reflection.MonoMethod.Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo) <0x0009f>
at System.Reflection.MethodBase.Invoke (object,object[]) <0x00047>
at NativeCode.Mobile.AppCompat.Helpers.KeyboardHelper.HideKeyboard (Android.Views.View) <0x0005f>
at NativeCode.Mobile.AppCompat.Renderers.Renderers.AppCompatEntryRenderer.Android.Widget.TextView.IOnEditorActionListener.OnEditorAction (Android.Widget.TextView,Android.Views.InputMethods.ImeAction,Android.Views.KeyEvent) <0x00047>
at Android.Widget.TextView/IOnEditorActionListenerInvoker.n_OnEditorAction_Landroid_widget_TextView_ILandroid_view_KeyEvent_ (intptr,intptr,intptr,int,intptr) <0x0008f>
at (wrapper dynamic-method) object.24094c1d-3bde-4d49-83c0-80574dac7cf6 (intptr,intptr,intptr,int,intptr) <0x00063>

at md5c481f02bc5e6c423b16497efaa5c312e.AppCompatEntryRenderer.n_onEditorAction(Native Method)
at md5c481f02bc5e6c423b16497efaa5c312e.AppCompatEntryRenderer.onEditorAction(AppCompatEntryRenderer.java:74)
at android.widget.TextView.onEditorAction(TextView.java:5148)
at com.android.internal.widget.EditableInputConnection.performEditorAction(EditableInputConnection.java:139)
at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:304)
at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:78)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5832)

Device: Galaxy S5 (klte)
Android 5.0

**Comment by mikepham** [comment]
Can you list what Xamarin version(s) you're using and what NuGet package versions?

**Comment by kierepka** [comment]
Xamarin Studio
Version 5.9.7 (build 9)
Runtime:
    Mono 4.0.4 ((detached/cb6d6b2)
    GTK+ 2.24.23 (Raleigh theme)
Xamarin.Android
Version: 5.1.6.7 (Business Edition)
    Supported Android versions:
        2.3   (API level 10)
        4.0.3 (API level 15)
        4.1   (API level 16)
        4.2   (API level 17)
        4.3   (API level 18)
        4.4   (API level 19)
        5.0   (API level 21)
        5.1   (API level 22)
Operating System
Mac OS X 10.10.5

Now with latest version of packages (1.0.0.78) I got this new error:
Do not request Window.FEATURE_ACTION_BAR and set windowActionBar to false in your theme to use a Toolbar instead.
